// <auto-generated />
using System;
using ApiServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717075722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ApiServer.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 3,
                            Title = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 4,
                            Title = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 3,
                            Title = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Credits = 3,
                            Title = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Credits = 5,
                            Title = "Programming 1"
                        },
                        new
                        {
                            Id = 6,
                            Credits = 5,
                            Title = "Programming 2"
                        },
                        new
                        {
                            Id = 7,
                            Credits = 2,
                            Title = "History"
                        },
                        new
                        {
                            Id = 8,
                            Credits = 2,
                            Title = "Geography"
                        },
                        new
                        {
                            Id = 9,
                            Credits = 1,
                            Title = "Art"
                        },
                        new
                        {
                            Id = 10,
                            Credits = 1,
                            Title = "Music"
                        });
                });

            modelBuilder.Entity("ApiServer.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 3
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 7,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 8,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 4
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 5
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 9,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 5
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 6
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 10,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 6
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 7,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 7
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 7
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 8,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 8
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 8
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 9,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 9
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 9
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 10,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 10
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("ApiServer.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Age = 19,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Age = 21,
                            Name = "Diana"
                        },
                        new
                        {
                            Id = 5,
                            Age = 23,
                            Name = "Edward"
                        },
                        new
                        {
                            Id = 6,
                            Age = 20,
                            Name = "Fiona"
                        },
                        new
                        {
                            Id = 7,
                            Age = 24,
                            Name = "George"
                        },
                        new
                        {
                            Id = 8,
                            Age = 18,
                            Name = "Hannah"
                        },
                        new
                        {
                            Id = 9,
                            Age = 22,
                            Name = "Ian"
                        },
                        new
                        {
                            Id = 10,
                            Age = 19,
                            Name = "Julia"
                        });
                });

            modelBuilder.Entity("ApiServer.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Street 1",
                            Phone = "555-001",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Street 2",
                            Phone = "555-002",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Street 3",
                            Phone = "555-003",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "Street 4",
                            Phone = "555-004",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "Street 5",
                            Phone = "555-005",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            Address = "Street 6",
                            Phone = "555-006",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            Address = "Street 7",
                            Phone = "555-007",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            Address = "Street 8",
                            Phone = "555-008",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 9,
                            Address = "Street 9",
                            Phone = "555-009",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 10,
                            Address = "Street 10",
                            Phone = "555-010",
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("ApiServer.Models.Enrollment", b =>
                {
                    b.HasOne("ApiServer.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiServer.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ApiServer.Models.StudentProfile", b =>
                {
                    b.HasOne("ApiServer.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ApiServer.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
